Repository UPRI-NOAH/noah-frontend, pull requests merged in 2023-08, with the labels that each got.

#336 fix(qc-iot): add latest data in popup map display
  CHANGELOG.md
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: enhancement, qc-iot

#338 feat(know-your-hazard): larger map mobile view
  src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html
Labels: enhancement

#339 fix(mobile-app): adjust search button and map display in kyh page
  src/app/features/know-your-hazards/pages/base/base.component.html
  src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html
  src/app/features/know-your-hazards/store/kyh.store.ts
Labels: documentation
