Repository UPRI-NOAH/noah-frontend, pull requests merged in 2023-09, with the labels that each got.

#340 feat(4as-modal): popup modal when calculate risk button is clicked
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.html
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.ts
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
  src/app/features/noah-playground/services/modal.service.ts
Labels: 4as

#342 feat(4as): add data in modal risk assessment
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
  src/app/features/noah-playground/services/risk-assessment.service.ts
  src/app/shared/components/summary/summary.component.html
Labels: 4as

#344 feat(iot): modal for safari testing
  src/app/features/home/components/footer/footer.component.html
  src/app/features/home/components/navigation/navigation.component.html
  src/app/features/know-your-hazards/pages/base/base.component.html
  src/app/features/noah-playground/components/qc-sensors-group/qc-sensors-group.component.html
  src/app/features/noah-playground/components/qc-sensors-group/qc-sensors-group.component.ts
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
  src/app/features/noah-playground/services/modal-services.service.ts
  src/app/shared/components/disclaimer/disclaimer.component.html
  src/app/shared/components/login/login.component.html
  src/app/shared/components/qc-login/qc-login.component.html
  src/app/shared/components/summary/summary.component.html
  src/app/shared/components/summary/summary.component.ts
  src/assets/icons/noah_logo.png
  src/assets/icons/noah_text.png
  src/assets/icons/up.png
  src/assets/icons/upri.png
Labels: bug, enhancement

#345 fix(iot): update modal service for iot
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
  src/app/features/noah-playground/components/qc-sensors-group/qc-sensors-group.component.ts
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
  src/app/features/noah-playground/services/modal.service.ts
  src/app/shared/components/alert/alert.component.ts
  src/app/shared/components/login/login.component.ts
  src/app/shared/components/qc-login/qc-login.component.ts
  src/app/shared/components/summary/summary.component.ts
Labels: bug, qc-iot, noah

#346 feat(4as): display population affected in map and list of affected population in modal
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.html
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.scss
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.ts
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
  src/app/features/noah-playground/services/modal.service.ts
  src/app/features/noah-playground/services/noah-playground.service.ts
  src/app/features/noah-playground/services/risk-assessment.service.ts
  src/app/shared/pipes/search-risk-affected.pipe.spec.ts
  src/app/shared/pipes/search-risk-affected.pipe.ts
  src/app/shared/shared.module.ts
Labels: enhancement, 4as
