Repository UPRI-NOAH/noah-frontend, pull requests merged in 2023-03, with the labels that each got.

#313 feat(qc-iot): hovering chart value in 2 decimal places
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
  src/app/features/noah-playground/services/qc-sensor-chart.service.ts
Labels: enhancement

#314 feat(qc-iot): battery percentage
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: qc-iot

#316 fix(kyh): add debris flow in assessment in know your hazard page
  src/app/features/know-your-hazards/services/hazards.service.ts
  src/app/features/know-your-hazards/services/kyh.service.ts
  src/app/shared/data/kyh_combined_tileset.json
Labels: enhancement, noah

#319 feat(kyh): add draggable marker location for new assessments
  src/app/core/services/map.service.ts
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.ts
  src/app/shared/components/search/search.component.ts
Labels: enhancement

#321 WIP(KYH): added tip for draggable and kyh legend
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.html
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.ts
  src/app/features/know-your-hazards/pages/base/base.component.html
Labels: enhancement

#322 fix(kyh): remove KYH legend
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.html
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.ts
Labels: Epic

#323 fix(noah-studio): change default color for hazard layers
  src/app/features/home/components/footer/footer.component.html
  src/app/features/noah-playground/store/noah-playground.store.ts
Labels: enhancement, noah
