Repository UPRI-NOAH/noah-frontend, pull requests merged in 2023-02, with the labels that each got.

#301 fix(qc-studio): fix ui for summary dashboard and name sensor type
  src/app/features/noah-playground/components/qc-sensor-solo/qc-sensor-solo.component.ts
  src/app/features/noah-playground/components/qc-sensors-group/qc-sensors-group.component.html
  src/app/shared/components/summary/summary.component.html
  src/app/shared/components/summary/summary.component.scss
Labels: enhancement, qc-iot

#303 feat(qc-iot): added unit for iot dot, KYH legend
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.html
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.ts
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
  src/app/features/noah-playground/services/qc-sensor.service.ts
  src/app/shared/components/summary/summary.component.html
  src/app/shared/components/summary/summary.component.ts
Labels: enhancement, qc-iot

#304 feat(kyh): update kyh legend in map
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.html
Labels: enhancement, noah

#302 feat(qc-iot): add Quezon City Municipal boundary
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
  src/app/features/noah-playground/components/qc-boundary/qc-boundary.component.html
  src/app/features/noah-playground/components/qc-boundary/qc-boundary.component.scss
  src/app/features/noah-playground/components/qc-boundary/qc-boundary.component.spec.ts
  src/app/features/noah-playground/components/qc-boundary/qc-boundary.component.ts
  src/app/features/noah-playground/components/qc-sensors-group/qc-sensors-group.component.html
  src/app/features/noah-playground/components/qc-sensors-group/qc-sensors-group.component.ts
  src/app/features/noah-playground/noah-playground.module.ts
  src/app/features/noah-playground/services/noah-playground.service.ts
  src/app/features/noah-playground/services/qc-sensor.service.ts
  src/app/features/noah-playground/store/noah-playground.store.ts
  src/app/shared/components/summary/summary.component.scss
  src/assets/map-sprites/square.png
Labels: enhancement, qc-iot

#305 feat(qc-iot): chart default to all
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: bug, enhancement

#306 fix(qc-iot): fix bugs from QA
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
  src/app/features/noah-playground/store/noah-playground.store.ts
Labels: bug, qc-iot

#307 fix(playground): remove 24hour lapse contour
  src/app/features/noah-playground/components/contour-maps/contour-maps.component.ts
  src/app/features/noah-playground/store/noah-playground.store.ts
Labels: enhancement, noah

#308 feat(qc-iot): QA fixed for hovering sensor
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: bug, enhancement

#310 fix(qc-iot-qa): when IoT sidebar unchecked hide popup
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: bug, enhancement

#309 fix(qc-iot): change QC boundary legend
  src/app/features/noah-playground/components/qc-boundary/qc-boundary.component.html
  src/assets/map-sprites/rect.png
  src/assets/map-sprites/square.png
Labels: enhancement, qc-iot

#311 feat(qc-iot): qa chart IoT graph
  src/app/features/noah-playground/services/qc-sensor-chart.service.ts
Labels: enhancement

#312 fix(qc-iot): change rain gauge title in summary dashboard
  src/app/shared/components/summary/summary.component.html
Labels: enhancement, qc-iot
