Repository UPRI-NOAH/noah-frontend, pull requests merged in 2024-10, with the labels that each got.

#411 fix(logout): bugs for logout
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
  src/app/features/noah-playground/services/qc-login.service.ts
  src/app/shared/components/login/login.component.html
  src/app/shared/components/login/login.component.ts
  src/app/shared/components/qc-login/qc-login.component.html
  src/app/shared/components/qc-login/qc-login.component.ts
Labels: bug

#412 fix(bug-noah): iot download file type data
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: bug

#413 fix(marker-kyh): double marker
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.ts
Labels: bug

#414 Fix(pwa): KYH survival page bug
  src/app/features/know-your-hazards/pages/base/base.component.html
  src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html
  src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.ts
Labels: bug

#417 fix(landslide): unstable slope tab
  src/app/shared/data/kyh_combined_tileset.json
  src/app/shared/mocks/hazard-types-and-levels.ts
Labels: noah

#416 fix(pwa-iot): touch iot sensor in mobile display
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: bug, qc-iot, pwa

#418 chore: update changelog
  CHANGELOG.md
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: noah
