Repository UPRI-NOAH/noah-frontend, pull requests merged in 2024-08, with the labels that each got.

#392 feat(home): donate in navigation
  src/app/features/home/components/navigation/navigation.component.html
Labels: noah

#391 fix(noah): update coordinates display when pin is move in kyh and studio
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.ts
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: enhancement, noah

#394 feat(studio)(exposure-assessment)[PWA]: Design mobile view for exposure assessment summary dashboard and optimize NOAH Studio nav list for mobile view
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
  src/app/features/noah-playground/services/risk-assessment.service.ts
Labels: pwa

#396 feat(studio)(qc-iot)(qc-summary)[PWA]: Design mobile view for IoT summary dashboard
  src/app/shared/components/summary/summary.component.html
  src/app/shared/components/summary/summary.component.ts
  src/assets/icons/close-button.png
  src/assets/icons/down-chevron.png
  src/assets/icons/search-icon.png
  src/assets/icons/sort-icon.png
  src/assets/images/Flood Scale.svg
  src/assets/images/Rain Scale.svg
  src/environments/environment.ts
Labels: pwa

#399 [WIP] NOAH Website PWA Conversion
  angular.json
  ngsw-config.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/features/home/components/navigation/navigation.component.html
  src/app/features/home/components/navigation/navigation.component.ts
  src/assets/icons/noah-logo-high-res.png
  src/assets/pwa-icons/apple-icon-180.png
  src/assets/pwa-icons/manifest-icon-192.maskable.png
  src/assets/pwa-icons/manifest-icon-512.maskable.png
  src/assets/pwa-splash-screens/apple-splash-1125-2436.jpg
  src/assets/pwa-splash-screens/apple-splash-1136-640.jpg
  src/assets/pwa-splash-screens/apple-splash-1170-2532.jpg
  src/assets/pwa-splash-screens/apple-splash-1179-2556.jpg
  src/assets/pwa-splash-screens/apple-splash-1242-2208.jpg
  src/assets/pwa-splash-screens/apple-splash-1242-2688.jpg
  src/assets/pwa-splash-screens/apple-splash-1284-2778.jpg
  src/assets/pwa-splash-screens/apple-splash-1290-2796.jpg
  src/assets/pwa-splash-screens/apple-splash-1334-750.jpg
  src/assets/pwa-splash-screens/apple-splash-1488-2266.jpg
  src/assets/pwa-splash-screens/apple-splash-1536-2048.jpg
  src/assets/pwa-splash-screens/apple-splash-1620-2160.jpg
  src/assets/pwa-splash-screens/apple-splash-1640-2360.jpg
  src/assets/pwa-splash-screens/apple-splash-1668-2224.jpg
  src/assets/pwa-splash-screens/apple-splash-1668-2388.jpg
  src/assets/pwa-splash-screens/apple-splash-1792-828.jpg
  src/assets/pwa-splash-screens/apple-splash-2048-1536.jpg
  src/assets/pwa-splash-screens/apple-splash-2048-2732.jpg
  src/assets/pwa-splash-screens/apple-splash-2160-1620.jpg
  src/assets/pwa-splash-screens/apple-splash-2208-1242.jpg
  src/assets/pwa-splash-screens/apple-splash-2224-1668.jpg
  src/assets/pwa-splash-screens/apple-splash-2266-1488.jpg
  src/assets/pwa-splash-screens/apple-splash-2360-1640.jpg
  src/assets/pwa-splash-screens/apple-splash-2388-1668.jpg
  src/assets/pwa-splash-screens/apple-splash-2436-1125.jpg
  src/assets/pwa-splash-screens/apple-splash-2532-1170.jpg
  src/assets/pwa-splash-screens/apple-splash-2556-1179.jpg
  src/assets/pwa-splash-screens/apple-splash-2688-1242.jpg
  src/assets/pwa-splash-screens/apple-splash-2732-2048.jpg
  src/assets/pwa-splash-screens/apple-splash-2778-1284.jpg
  src/assets/pwa-splash-screens/apple-splash-2796-1290.jpg
  src/assets/pwa-splash-screens/apple-splash-640-1136.jpg
  src/assets/pwa-splash-screens/apple-splash-750-1334.jpg
  src/assets/pwa-splash-screens/apple-splash-828-1792.jpg
  src/index.html
  src/manifest.webmanifest
Labels: pwa

#403 fix(pwa): kyh pwa UI and functions
  src/app/features/know-your-hazards/components/hazard-button/hazard-button.component.html
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.html
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.ts
  src/app/features/know-your-hazards/pages/base/base.component.html
  src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html
Labels: pwa
