Repository UPRI-NOAH/noah-frontend, pull requests merged in 2024-02, with the labels that each got.

#352 feat(4as): disclaimer IoT and 4as responsive, also the bug when search
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.ts
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
  src/app/features/noah-playground/services/modal.service.ts
  src/app/shared/components/alert/alert.component.html
  src/app/shared/components/alert/alert.component.ts
  src/app/shared/components/disclaimer/disclaimer.component.html
  src/assets/images/iesm-logo.png
  src/assets/images/tufts-logo.png
  src/assets/images/upri_logo_text.png
  src/assets/images/usaid-logo.png
Labels: 4as

#353 fix(4as): change legend for rain forecast and population and adjust whitespace in mobile view
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.html
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
  src/assets/legends/rainfall-forecast-legend.png
Labels: enhancement, 4as

#337 feat(4as): staging branch for exposure assessment feature in noah studio
  CHANGELOG.md
  src/app/features/noah-playground/components/laguna-sensor-solo/laguna-sensor-solo.component.html
  src/app/features/noah-playground/components/laguna-sensor-solo/laguna-sensor-solo.component.spec.ts
  src/app/features/noah-playground/components/laguna-sensor-solo/laguna-sensor-solo.component.ts
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
  src/app/features/noah-playground/components/risk-assessment-exposure/risk-assessment-exposure.component.html
  src/app/features/noah-playground/components/risk-assessment-exposure/risk-assessment-exposure.component.scss
  src/app/features/noah-playground/components/risk-assessment-exposure/risk-assessment-exposure.component.spec.ts
  src/app/features/noah-playground/components/risk-assessment-exposure/risk-assessment-exposure.component.ts
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.html
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.scss
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.spec.ts
  src/app/features/noah-playground/components/risk-assessment-group/risk-assessment-group.component.ts
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.scss
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.spec.ts
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
  src/app/features/noah-playground/components/risk-assessment-rain/risk-assessment-rain.component.html
  src/app/features/noah-playground/components/risk-assessment-rain/risk-assessment-rain.component.scss
  src/app/features/noah-playground/components/risk-assessment-rain/risk-assessment-rain.component.spec.ts
  src/app/features/noah-playground/components/risk-assessment-rain/risk-assessment-rain.component.ts
  src/app/features/noah-playground/noah-playground.module.ts
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.scss
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
  src/app/features/noah-playground/services/modal.service.ts
  src/app/features/noah-playground/services/noah-playground.service.ts
  src/app/features/noah-playground/services/risk-assessment.service.ts
  src/app/features/noah-playground/store/noah-playground.store.ts
  src/app/shared/components/alert/alert.component.html
  src/app/shared/components/alert/alert.component.ts
  src/app/shared/components/disclaimer/disclaimer.component.html
  src/app/shared/pipes/search-risk-affected.pipe.spec.ts
  src/app/shared/pipes/search-risk-affected.pipe.ts
  src/app/shared/shared.module.ts
  src/assets/images/iesm-logo.png
  src/assets/images/tufts-logo.png
  src/assets/images/upri_logo_text.png
  src/assets/images/usaid-logo.png
  src/assets/legends/rainfall-forecast-legend.png
Labels: Epic, 4as

#354 feat(4as): Exposure Assessment data summary and UI
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
  src/app/features/noah-playground/services/risk-assessment.service.ts
  src/app/shared/components/alert/alert.component.html
  src/assets/images/4as.png
  src/assets/images/wm-logo.jpg
  src/assets/legends/rainfall-forecast-legend.png
Labels: 4as

#355 fix(4as): issue date time dropdown in summary dashboard
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
Labels: 4as

#356 fix(4as): rain forecast coordinates
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: 4as

#357 fix(4as): responsive popup and archive download data and fix duplicating data
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.scss
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
  src/app/features/noah-playground/services/modal.service.ts
  src/app/shared/components/alert/alert.component.html
  src/app/shared/components/alert/alert.component.ts
Labels: 4as

#358 fix(4as): fix header in summary table
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.scss
Labels: enhancement, 4as
