Repository UPRI-NOAH/noah-frontend, pull requests merged in 2024-03, with the labels that each got.

#359 feat(4as): archive button and download
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.scss
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
Labels: 4as

#360 feat(main): hide contour and sensor
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
Labels: noah

#361 feat(noah): calculation of distance and area
  package-lock.json
  package.json
  src/app/features/noah-playground/components/map-playground/map-playground.component.html
  src/app/features/noah-playground/components/map-playground/map-playground.component.scss
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
  src/assets/icons/delete-distance.svg
  src/assets/icons/distance.svg
  src/index.html
Labels: enhancement

#362 fix(noah): closing of plotted distance
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
Labels: bug

#363 fix(4as): freeze header in table summary
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.scss
Labels: enhancement, 4as
