Repository UPRI-NOAH/noah-frontend, pull requests merged in 2024-09, with the labels that each got.

#404 fix(pwa-studio): PWA for large and mobile sidebar
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
Labels: enhancement, pwa

#406 fix(pwa-ea): placeholder for sorting modal exposure assessment
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
Labels: pwa

#407 fix(sidebar): pwa sidebar mobile devices drag
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
Labels: pwa

#408 Fix(summary-dashboard):
  src/app/shared/components/summary/summary.component.html
  src/app/shared/components/summary/summary.component.ts
Labels: pwa

#405 fix(kyh-pwa): mobile view sidebar
  src/app/features/know-your-hazards/components/map-kyh/map-kyh.component.html
  src/app/features/know-your-hazards/pages/base/base.component.html
  src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html
  src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.ts
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.ts
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.ts
  src/app/features/noah-playground/services/risk-assessment.service.ts
Labels: pwa

#409 fix(pwa-kyh): adjust screen size for mobile devices
  src/app/features/know-your-hazards/pages/know-your-hazards/know-your-hazards.component.html
Labels: pwa

#410 fix(pwa-dashboard): fix sort button in summary and exposure assessment dashboard
  src/app/features/noah-playground/components/map-playground/map-playground.component.ts
  src/app/features/noah-playground/components/risk-assessment-modal/risk-assessment-modal.component.html
  src/app/features/noah-playground/pages/noah-playground/noah-playground.component.html
  src/app/shared/components/summary/summary.component.html
  src/assets/icons/close-button.png
Labels: enhancement, pwa

#400 feat(angular update): Upgrading angular 11 to 12
  package.json
Labels: noah
